version: "3.7"

services:
        web:
                image: alpine:latest
                build:
                        context: ./web
                ports:
                        - "80:80"
                        - "443:443"
                        - "8000:8000"
                        - "9001:9001"
                        - "9002:9002"
                volumes:
                        - ./web/site.conf:/etc/nginx/nginx.conf
                networks:
                        - webapp
                depends_on:
                        - python

        python:
                tty: true
                volumes:
                        - ./python:/rayweb
                image: python:latest
                build:
                        context: ./python
                networks:
                        - webapp

networks:
        webapp:
