version: "3.7"

services:
        web:
                image: nginx:latest
                ports:
                        - "80:80"
                volumes:
                        - ./site.conf:/etc/nginx/nginx.conf
                networks:
                        - webapp

        python:
                image: python:3.7-stretch
                build:
                        context: .
                networks:
                        - webapp
                depends-on:
                        - web

        networks:
                webapp:
